collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#C4C7CF'
    - '#212021'
    - '#A4ABB3'
  rhythmicContrast: 0
typography_spectrum: 0.7601145
layout_spectrum: 0.1726493
name: Portraits I Love
