layout_spectrum: 0.1726493
typography_spectrum: 0.7601145
color:
  saturation: 0.9613916
  lightness: 0.1310908
  brandStrength: 0.487252
  rhythmicContrast: 0.1757573
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Portraits I Love
